### PR TITLE
feat:add contributors.rst

### PR DESCRIPTION
**Pull request by nirajandata**

### CODE REVIEW

**Review by Aju100 — CHANGES_REQUESTED** [review]
@nirajandata  ,

Remove ou the content and only list contributors one also rename the file as contributors.rst.
ex:
```
- Mr. Aju Tamang is the main contributor and the owner of the project. He have inspired lots of young developer for contributing to opensource projects.
- Mr. Roman Shrestha have done a lot of contributions for making the project more secured and added some features like fake admin panel
- Mr. Nirajan Dhakal has made some changes on the admin panel of this project and managed to fixsome issues on the projects.

```

**Comment by Romansth** [comment]
@Aju100 @nirajandata Isn't the file name supposed to be CONTRIBUTERS.rst ? Because contributing.rst is supposed to be the file name for contribution guidelines.

**Comment by Aju100** [comment]
> @Aju100 @nirajandata Isn't the file name supposed to be CONTRIBUTERS.rst ? Because contributing.rst is supposed to be the file name for contribution guidelines.

yeah. needs to request him through the feedbacks.

**Comment by nirajandata** [comment]
thanks @Romansth  and @Aju100 , i will change the name to contributing.rst

**Review by Aju100 — APPROVED** [review]
Great @nirajandata

**Pull request merged**
