### PR TITLE
fixed issue no module found called apps 

### PR DESCRIPTION
**Pull request by nirajandata**

### CODE REVIEW

**Review by Aju100 — COMMENTED** [review]
HI @nirajandata,
can you explain me this snippet.
```
import sys
ROOT_DIR = Path(__file__).resolve(strict=True).parent.parent.parent
main_dir=str(ROOT_DIR)+'/main/'
sys.path.append(main_dir)
import apps
```

I think without the addition of this code too, it will run correct me if I am wrong.

**Review by Aju100 — COMMENTED** [review]
Hi @nirajandata,

I didn't see the updates of #36 issue. Did you move it or delete the app or not ?

**Comment by nirajandata** [comment]
i moved the app

**Comment by nirajandata** [comment]
i think i put that in comment as moving the main app to todo dir will do the work , so i commented it and it's okay to remove it

**Comment by Aju100** [comment]
Hi @nirajandata Looks like it's okay but can you delete that uncomment one and rename the whole commit name.

Guide for commit message:
- https://csaju.com/blog/how-to-write-a-good-commit-message/

Renaming commit message:
- https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages
- https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by nirajandata** [comment]
okay

**Pull request closed without merging**
