### PR TITLE
feat:contribution-guidelines-added

### PR DESCRIPTION
**Pull request by Romansth**
A new file CONTRIBUTING.rst has been added which consists of guidelines to be followed while contributing to this project. Also, the guidelines have been referenced on README.rst of this project.

### CODE REVIEW

**Comment by Aju100** [comment]
Hi @Romansth ,

This task was assigned to @nirajandata . 

Link: https://github.com/Aju100/Django-Backend-mentorship/pull/53

Your task: https://github.com/Aju100/Django-Backend-mentorship/issues/51

**Review by Aju100 — CHANGES_REQUESTED** [review]
Send me the screenshots of it.

**Comment by Romansth** [comment]
https://user-images.githubusercontent.com/53575561/120761507-fbe51e00-c534-11eb-9302-06ca822aac00.png

**Comment by Romansth** [comment]
image

**Pull request merged**
