### PR TITLE
feat: Tests for tasks model added

### PR DESCRIPTION
**Pull request by Romansth**
I've added tests for tasks model inside the main app and ran it successfully.
image

### CODE REVIEW

**Comment by Romansth** [comment]
@Aju100  any idea on how I can fix this pre-commit error?

**Comment by Aju100** [comment]
> @Aju100 any idea on how I can fix this pre-commit error?

This is due to the problem of linting of your written code. Do check out the errors in Github action results. Also, I prefer you to install pre-commit and fixed the issue by linting your code base.

**Review by Aju100 — CHANGES_REQUESTED** [review]
Also try out the coverage and show the result of it.

**Comment by Romansth** [comment]
image

**Review by Aju100 — CHANGES_REQUESTED** [review]
coverage is okay but needs more exceptions handling unit tests too. Also, did you run the test on your machine?

**Comment by Romansth** [comment]
Yes, I've tested it on my local machine.

**Comment by Romansth** [comment]
Okay I'll add some exception handling unit tests too

**Comment by Aju100** [comment]
@Romansth I will merge but there all lots of things to do for it. thanks

**Pull request merged**
