### PR TITLE
Django Admin customize

### PR DESCRIPTION
**Pull request by nirajandata**

### CODE REVIEW

**Review by Aju100 — COMMENTED** [review]
@nirajandata can you explain summary of the code of each module so we can know what it really does and also did you maintain pep8 standard. If you haven't you can use from the following resources:
- https://www.python.org/dev/peps/pep-0008/
- https://realpython.com/python-pep8/

**Comment by nirajandata** [comment]
Yes , i can explain you the summary of my code . Yes , i tried to maintain the pep standard too .

**Comment by Aju100** [comment]
> Yes , i can explain you the summary of my code . Yes , i tried to maintain the pep standard as much as i can . For some files , i intentionally had to import it after the variable creation of the codebase since they belong to different sub directories and to be able to import them properly , i kept some variables above import stuffs

Can you please share the Screenshot of the admin section which you have customized?

**Review by Aju100 — APPROVED** [review]

**Review by Aju100 — APPROVED** [review]
Looks good awesome @nirajandata

**Pull request merged**
